apps/blog/models.py
from datetime import datetime

from flask import url_for
import sqlalchemy as sq

from application import db


class Blog(db.Model):
    __tablename__ = 'blog'

    id = sq.Column(sq.Integer, primary_key=True)
    slug = sq.Column(sq.String, unique=True, nullable=False)
    title = sq.Column(sq.String, nullable=False)
    content = sq.Column(sq.String, nullable=False)
    date = sq.Column(sq.DateTime, default=datetime.utcnow)

    author_id = sq.Column(sq.Integer, sq.ForeignKey('user.id'))

    def get_absolute_url(self):
        return url_for('blog.detail', slug=self.slug)

    def __repr__(self):
        return f"<Blog {self.title}>"


class Comment(db.Model):
    __tablename__ = 'comment'

    id = sq.Column(sq.Integer, primary_key=True)
    text = sq.Column(sq.String, nullable=False)

    author_id = sq.Column(sq.Integer, sq.ForeignKey('user.id', ondelete='CASCADE'))
    blog_id = sq.Column(sq.Integer, sq.ForeignKey('blog.id', ondelete='CASCADE'))
    date = sq.Column(sq.DateTime, default=datetime.utcnow)

apps/blog/forms.py
import re

from flask_ckeditor import CKEditorField
from flask_wtf import FlaskForm
import wtforms
import wtforms.validators as validators

from apps.blog import Blog
from mixins.modelform import ModelFormMixin
from services.unique_slugify import unique_slugify


class BlogForm(ModelFormMixin, FlaskForm):
    model = Blog

    slug = wtforms.StringField("Slug", validators=[
        validators.Regexp('^[a-z0-9-]*$',
                          message="In slug allowed only lowercase letters, numbers, '-' char")
    ])
    title = wtforms.StringField("Title", validators=[validators.InputRequired()])
    content = CKEditorField('Content', validators=[validators.InputRequired()])

    def validate_title(self, field):
        if len(re.sub('[^aA-zZ\d]', '', self.title.data)) < 5:
            raise validators.ValidationError("Too short title")
        return field

    def validate_slug(self, field):
        if field.data == "":
            field.data = unique_slugify(self.get_instance(), self.title.data)
        elif Blog.query.filter(Blog.slug == field.data, Blog.id != self.get_instance().id).first():
            raise validators.ValidationError("Given slug already in use")

        return field


class CommentForm(FlaskForm):
    text = CKEditorField('Comment', validators=[validators.InputRequired(), validators.Length(min=15)])

apps/blog/__init__.py
from flask import Blueprint

from .models import *

blog = Blueprint('blog', __name__, template_folder='templates', static_folder='static')

from .routes import *

apps/blog/routes.py
from flask import request, render_template, abort, redirect, url_for, flash
from flask_login import login_required, current_user

from application import db
from apps.authorization import User
from apps.blog import Blog, blog as app, Comment
from apps.blog.forms import BlogForm, CommentForm


@app.route('/')
def list():
    paginator = Blog.query.paginate(per_page=5, error_out=False)
    page = request.args.get('page', 1, int)
    if page > paginator.pages > 0:
        return redirect(request.base_url)
    paginator.page = page
    return render_template('blog/list.html', page_obj=paginator, display_more_pages=2)


@app.route('/view/<string:slug>', methods=['POST', 'GET'])
def detail(slug):
    blog = Blog.query.filter_by(slug=slug).first()
    if blog is None:
        abort(404)

    form = None

    # Adding comments to blog
    if current_user.is_authenticated:
        # Check for comment per user limit
        if Comment.query.filter_by(blog_id=blog.id, author_id=current_user.id).count() < 3:

            form = CommentForm()
            if form.validate_on_submit():
                comment = Comment(text=form.text.data, blog_id=blog.id, author_id=current_user.id)

                db.session.add(comment)
                db.session.commit()
                flash("You comment sent")

                return redirect(blog.get_absolute_url())

    comments = db.session.query(Comment.text, Comment.date, User.username).join(User, Comment.blog_id == blog.id and User.id == Comment.author_id)

    return render_template('blog/detail.html', object=blog, form=form,
                           comments=comments,
                           breadcrumbs=[("Main", '/'), (blog.title,)]
                           )


@app.route("/add", methods=['POST', 'GET'])
@login_required
def add_blog():
    form = BlogForm()

    if form.validate_on_submit():
        blog: Blog = form.save()
        blog.author_id = current_user.id

        db.session.add(blog)
        db.session.commit()

        flash(f"Blog {blog.title} created")

        return redirect(blog.get_absolute_url())

    return render_template('blog/create.html', form=form,
                           breadcrumbs=[("Main", '/'), ("Add blog",)])


@app.route("/edit/<string:slug>", methods=['POST', 'GET'])
@login_required
def edit_blog(slug):
    blog: Blog = Blog.query.filter_by(slug=slug, author_id=current_user.id).first()
    if blog is None:
        abort(404)

    form = BlogForm(instance=blog)

    if form.validate_on_submit():
        blog = form.save()
        db.session.add(blog)
        db.session.commit()

        flash(f"Blog {blog.title} updated")

        return redirect(blog.get_absolute_url())
    return render_template('blog/edit.html', object=blog, form=form,
                           breadcrumbs=[("Main", '/'), (f"Edit blog `{blog.title}`",)])


@app.route('/delete/<string:slug>')
@login_required
def delete_blog(slug):
    blog: Blog = Blog.query.filter_by(slug=slug, author_id=current_user.id).first()
    if blog is None:
        abort(404)

    db.session.delete(blog)
    db.session.commit()

    flash(f"Blog {blog.title} has been deleted")

    return redirect(url_for(".list"))

apps/blog/templates/blog/create.html
{% extends 'base.html' %}
{% from 'macro/form.html' import print_form %}

{% block body %}
<form method="post">
    <div class="mx-4 px-5 py-5">
        <center><h4>Create blog</h4></center>
        {{ print_form(form) }}
        <hr>
        <center class="py-3">
            <button class="btn btn-primary" type="submit">Submit</button>
            <a class="btn btn-danger" href="{{ url_for('blog.list') }}">Back to main</a>
        </center>
    </div>
</form>

{{ ckeditor.load() }}

{% endblock body %}

apps/blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block body %}
<center>
    <h4>Blog {{ object.title }}</h4>
</center>

<div class="row">
    <div class="col-10"></div>
    <div class="col">
        {% if current_user.is_authenticated and current_user.id == object.author_id %}
            <a href="{{ url_for('blog.edit_blog', slug=object.slug) }}" class="btn btn-success">Edit</a>
        {% endif %}
    </div>
</div>

<div class="row">
    {{ object.content|safe }}
    <p align="right">{{ object.date.strftime("%d %b %Y %I:%M %p") }}</p>
</div>

<div class="row">
      {% if form %}
        <hr>
        {% from 'macro/form.html' import print_form %}

        <form method="post">
            <center>
                <div class="col-md-8 col-lg-8" style="border: 2px solid black; border-radius: 5px">
                    <center><h4>Add comment</h4></center>
                    {{ print_form(form) }}
                    <center class="py-3">
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </center>
                </div>
            </center>

        </form>

    {% endif %}
</div>

<div class="row">
    <center>
        <h4>Comments</h4>
        <div class="col-md-8 col-lg-6">
            {% for comment in comments %}
                 <div class="card mb-4">
                  <div class="card-body">
                    {{ comment.text }}
                    <div class="d-flex justify-content-between">
                      <div class="d-flex flex-row align-items-center">
                        <img src="" alt="" width="25" height="25" />
                        <p class="small mb-0 ms-2">{{ comment.username }}</p>
                      </div>
                        <time class="small mb-0 ms-2 text-center">{{ comment.date }}</time>
                    </div>
                  </div>
                </div>
            {% endfor %}
        </div>
    </center>
</div>

{% endblock body %}

apps/blog/templates/blog/edit.html
{% extends 'base.html' %}
{% from 'macro/form.html' import print_form %}

{% block body %}
<form method="post">
    <div class="mx-4 px-5 py-5">
        <center><h4>Edit blog</h4></center>
        {{ print_form(form) }}
        <hr>
        <center class="py-3">
            <a class="btn btn-success" href="{{ object.get_absolute_url() }}">Back to view</a>
            <button class="btn btn-primary" type="submit">Submit</button>
            <a class="btn btn-danger" href="{{ url_for('blog.delete_blog', slug=object.slug) }}">Delete blog</a>
        </center>
    </div>
</form>

{{ ckeditor.load() }}

{% endblock body %}

apps/blog/templates/blog/list.html
{% extends 'base.html' %}

{% block body %}
<center>
    <h4>Blogs</h4>
</center>

<div class="row">
    <div class="col-10"></div>
    <div class="col">
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('blog.add_blog') }}" class="btn btn-primary">Create</a>
        {% endif %}
    </div>
</div>


<table class="table">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Name</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>

    {% for blog in page_obj.items %}
        <tr>
          <th scope="row">{{ blog.date.strftime("%d %b %Y %I:%M %p") }}</th>
          <td>{{ blog.title }}</td>
          <td><a href="{{ blog.get_absolute_url() }}" class="btn btn-primary">View</a></td>
        </tr>
    {% endfor %}
  </tbody>
</table>

  {% if page_obj.pages > 1 %}
            <nav aria-label="...">
              <ul class="pagination justify-content-center">
                {% if page_obj.has_prev %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ page_obj.page - 1 }}" tabindex="-1">Previous</a>
                    </li>
                {% else %}
                     <li class="page-item disabled">
                      <a class="page-link" href="" tabindex="-1">Previous</a>
                    </li>
                {% endif %}

                {% set display = display_more_pages + 1 %}

                {% for i in range(1, page_obj.pages + 1) %}
                    {% if page_obj.page - display < i < page_obj.page + display %}
                        <li class="page-item {% if i == page_obj.page %}active{% endif %}"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                  {% if page_obj.has_next %}
                      <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.page + 1 }}">Next</a>
                      </li>
                  {% else %}
                      <li class="page-item disabled">
                        <a class="page-link" href="">Next</a>
                      </li>
                  {% endif %}

              </ul>
            </nav>
    {% endif %}

{% endblock body %}